2024-08-25 23:11:51,249 / WARNING / Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\PythonProjects\pythonProjectGeneral\Homeworks\Module12\test_12_4.py", line 25, in test_run
    obj = m.Runner(50, 7)
  File "D:\PythonProjects\pythonProjectGeneral\Homeworks\Module12\module_12_4.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-08-25 23:11:51,250 / WARNING / Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\PythonProjects\pythonProjectGeneral\Homeworks\Module12\test_12_4.py", line 14, in test_walk
    obj = m.Runner('Ann', -5)
  File "D:\PythonProjects\pythonProjectGeneral\Homeworks\Module12\module_12_4.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
